### ISSUE TITLE
Nothing showing in game

### ISSUE THREAD

**Issue by Asher0990** [Jayick/Farming#1]
Downloaded and installed into a mod folder for the game.  When pressing f1 it says that the mod was loaded but getting into game there is nothing in the game.  Went and looked at the text in the mod folder and realized it was the same thing in both.  Just the basic info in both folders.  Was this accidental or am I missing something?

**Comment by Jayick** [comment]
Currently in the process of uploading it :) Should be done shortly. The files are not all here yet.

**Comment by Asher0990** [comment]
Thank you Jayick!  My pals and I are REALLY looking forward to this mod.  One of my friends is even waiting for it and willing to be pulled away from Kingdom Hearts 3 for this.  Saw the work in Jawoodle's video and it was amazing!  Thank you for the reply and all that you do.
