### ISSUE TITLE
XUI bug in multiplayer

### ISSUE THREAD

**Issue by samstinson** [Jayick/Farming#2]
Downloaded latest version on client and dedicated Linux server, a17 b9 stable. Attempting to access any of the workbenches results in an XUI error "WRN Window 'workstation_Farm Table' not found in XUI!"

https://steamcommunity.com/sharedfiles/filedetails/?id=1647433355

**Comment by Jayick** [comment]
Just released an update with a fix. Sorry about that!

**Comment by samstinson** [comment]
Updated to the latest version and this is still an issue.
